# Generated by Django 5.1.4 on 2025-04-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('ID_Trabajador', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=225)),
                ('monto_base', models.IntegerField(default=0)),
                ('bono_produccion', models.IntegerField(default=0)),
                ('hora_ordinaria', models.IntegerField(default=0)),
                ('hora_extra', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
    ]
