# Generated by Django 5.1.4 on 2025-04-28 02:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='total',
        ),
        migrations.AddField(
            model_name='trabajador',
            name='fecha_contrato',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
